### ISSUE TITLE
Your plugin was blacklisted

### ISSUE THREAD

**Issue by crissdev** [ValeryIvanov/gulp-props2json#1]
FYI, this plugin was reported [here](https://github.com/gulpjs/plugins/pull/197) because it is a clone of [gulp-props](https://www.npmjs.com/package/gulp-props).

**Comment by ValeryIvanov** [comment]
Sure its a clone but with feature that your plugin does not have. This repo and npm package was made only for me to use, but now I feel like competing with your plugin. I will try to find time, add more features and make this plugin more attractive for other users. Thanks!
